### ISSUE TITLE
2: Player - A lista de vídeos

### ISSUE THREAD

**Issue by eduardoliron** [Agreste/MobUrbRoteiro#2]
Temos` de ver o caminho do filme embaixo de alguma forma gráfica. Por exemplo:

ABERTURA > CASÉ01 > JÚLIO03 > BORBA 13 > ... > FECHAMENTO

de modo que possamos voltar o trecho pra ver, saber de quem é cada deriva, etc.
No caso da pessoa decidir ver outra deriva, a lista anterior deve ficar visível (e selecionável?) embaixo, enquanto a outra deriva se desenvolve... ex:
ABERTURA > JÚLIO01 > DIGA13 > ... > FECHAMENTO

ABERTURA > CASÉ01 > JÚLIO03 > BORBA 13 > ... > FECHAMENTO (menor, cinza calaro, sei la)

**Comment by aivuk** [comment]
Entendi a idéia de exibição sob o vídeo. Mas não entendi o que chamou de deriva. E esse passos abaixo, vão sendo exibidos na medida que o vídeo for passando? Note que atualmente quando dá play ele monta já uma trajetória completa da ABERTURA até o FECHAMENTO.

**Comment by eduardoliron** [comment]
pode mostrar tudo ja, mas salientar de alguma forma qual vídeo está sendo visto atualmente

**Comment by aivuk** [comment]
Fiz a lista dos vídeos abaixo do player, mas ainda não estou destacando o vídeo que está tocando no momento.

**Comment by aivuk** [comment]
Pronto, coloquei um estilo pra indicar qual parte do vídeo está assistindo no momento. Acho que agora é só melhorarmos o design, mas isso você consegue fazer fácil só via CSS, a não ser que queira fazer algo muito elaborado, pois neste caso teria que alterar o JS.
