### ISSUE TITLE
6: Links - Barra de endereço

### ISSUE THREAD

**Issue by eduardoliron** [Agreste/MobUrbRoteiro#6]
Se der, os links de montagem do video tinha de ficar mais intuitivo (ex: moburb.org/#B01#BG15#C03#DN06#DG09#DR10#J02#S02, etc,  no caso bergman, borba gato, casé, daniel, diga, drão, julio e sabrina, respectivamente... Algo assim.) de modo que se a pessoa quiser montar o filme dela ela consegue.

**Comment by aivuk** [comment]
Beleza, é possível, mas eu tentei achar uma solução que daria urls mais curtas, mas talvez isso não faça (muita) diferença. No modelo atual, o url da sequência:

https://o.moburb.org/CKq0vvQ0hYo0S0k0VO 

aponta pra um sequência com 15 segmentos, contando o final e a abertura. Se fosse usar seu sistema, excluindo os # e 0 que não são necessários, teríamos algo como:

https://o.moburb.org/B1BG15C3DN6DG9DR10J2S2C3DN6DG9DR10BG15

Fica maior, o que tu acha?

**Comment by eduardoliron** [comment]
Eu acho suave. Pode até trocar esse DN, dr, etc por a b c d e f g h (cada
pessoa e Borba), se preferir...

Ou mesmo 1 a 7 e vídeos ordenados em letra pra ser o e não 15.

Contanto que, se quisermos, fique fácil pra ensinar alguém a montar o seu.
Em 10 de mai de 2016 7:40 PM, "Edgar Z. Alvarenga" <notifications@github.com>
escreveu:

**Comment by aivuk** [comment]
Olha, se formos pensar que "alguém" irá montar, melhor pensar numa interface pra isso. No modelo atual cada símbolo A-Z, a-z e 0-9 no URL já corresponde a um dos nossos vídeos.

**Comment by eduardoliron** [comment]
imaginei... Tem de ser minimamente intuitivo
